[package]
name = "dynamic_pages"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
drain_common = "0.6.5"
drain_macros = "0.6.0"